from django.urls import path

from .views import (
    CategoryCreateView,
    CategoryDeleteView,
    CategoryImportView,
    CategoryListView,
    CategoryUpdateView,
    CreditCardCreateView,
    CreditCardDeleteView,
    CreditCardExpenseCreateView,
    CreditCardExpenseDeleteView,
    CreditCardExpenseUpdateView,
    CreditCardOverviewView,
    CreditCardPaymentCreateView,
    CreditCardPaymentDeleteView,
    CreditCardPaymentUpdateView,
    CreditCardUpdateView,
    DashboardView,
    MonthlySummaryView,
    TransactionCreateView,
    TransactionDeleteView,
    TransactionImportView,
    TransactionListView,
    TransactionUpdateView,
    download_category_import_template,
    download_transaction_import_template,
    export_transactions_csv,
)

app_name = 'finances'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('categorias/', CategoryListView.as_view(), name='category_list'),
    path('categorias/nova/', CategoryCreateView.as_view(), name='category_create'),
    path('categorias/importar/', CategoryImportView.as_view(), name='category_import'),
    path('categorias/modelo-importacao/', download_category_import_template, name='category_import_template'),
    path('categorias/<int:pk>/editar/', CategoryUpdateView.as_view(), name='category_update'),
    path('categorias/<int:pk>/excluir/', CategoryDeleteView.as_view(), name='category_delete'),
    path('lancamentos/', TransactionListView.as_view(), name='transaction_list'),
    path('lancamentos/novo/', TransactionCreateView.as_view(), name='transaction_create'),
    path('lancamentos/importar/', TransactionImportView.as_view(), name='transaction_import'),
    path('lancamentos/modelo-importacao/', download_transaction_import_template, name='transaction_import_template'),
    path('lancamentos/<int:pk>/editar/', TransactionUpdateView.as_view(), name='transaction_update'),
    path('lancamentos/<int:pk>/excluir/', TransactionDeleteView.as_view(), name='transaction_delete'),
    path('lancamentos/exportar-csv/', export_transactions_csv, name='transaction_export_csv'),
    path('cartoes/', CreditCardOverviewView.as_view(), name='credit_card_overview'),
    path('cartoes/novo/', CreditCardCreateView.as_view(), name='credit_card_create'),
    path('cartoes/<int:pk>/editar/', CreditCardUpdateView.as_view(), name='credit_card_update'),
    path('cartoes/<int:pk>/excluir/', CreditCardDeleteView.as_view(), name='credit_card_delete'),
    path('cartoes/despesas/nova/', CreditCardExpenseCreateView.as_view(), name='credit_card_expense_create'),
    path('cartoes/despesas/<int:pk>/editar/', CreditCardExpenseUpdateView.as_view(), name='credit_card_expense_update'),
    path('cartoes/despesas/<int:pk>/excluir/', CreditCardExpenseDeleteView.as_view(), name='credit_card_expense_delete'),
    path('cartoes/pagamentos/novo/', CreditCardPaymentCreateView.as_view(), name='credit_card_payment_create'),
    path('cartoes/pagamentos/<int:pk>/editar/', CreditCardPaymentUpdateView.as_view(), name='credit_card_payment_update'),
    path('cartoes/pagamentos/<int:pk>/excluir/', CreditCardPaymentDeleteView.as_view(), name='credit_card_payment_delete'),
    path('resumo-mensal/', MonthlySummaryView.as_view(), name='monthly_summary'),
]
